<a href="https://colab.research.google.com/github/BridgingAISocietySummerSchools/Python-for-Data-Science-Workshop/blob/main/01_introduction/01_welcome_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐍 Welcome to Python — Your First Steps

> **Track:** Introduction Session — Notebook 1 of 5 · **Estimated time:** ~15 min · **Difficulty:** complete beginner

Welcome! In the next quarter of an hour you will write your very first lines of Python — the language behind most of today's data science and AI. No coding experience needed: we go slowly, and everything you need is on this page.

## 🎯 Learning objectives

By the end of this notebook you will be able to:

1. Run code in a Jupyter notebook (and know what a notebook *is*).
2. Read Python's basic layout: statements top-to-bottom, and `#` comments.
3. Store values in **variables** and reuse them.
4. Name the four core **data types** — `int`, `float`, `str`, `bool` — and check them with `type()`.
5. Do **arithmetic** in Python and build readable output with **f-strings**.

## ✅ Prerequisites

None whatsoever. If you can use a web browser, you are ready.

➡️ **Next:** [`02_data_structures.ipynb`](02_data_structures.ipynb)

## 1. Hello! What is Python, and what is this page?

**Python** is a programming language — a way to give a computer precise, repeatable instructions. It dominates data science and AI for two reasons: it reads almost like English, and an enormous community has built free tools on top of it — for tables of data, for charts, for machine learning. When researchers analyse survey data, when a hospital builds a risk model, when a modern AI system is trained — Python was almost certainly involved.

**This page is a Jupyter notebook.** It mixes two kinds of cells:

- **Text cells** (like this one) — notes and explanations.
- **Code cells** — real Python that you can *run*.

To run a code cell: **click it, then press Shift + Enter** (or click the ▶ button). The result appears directly below the cell.

That's genuinely all you need to know. Let's run your first program — click the cell below and press **Shift + Enter**:

In [3]:
# Anything after a "#" is a comment — a note for humans. Python ignores it.

print("Hello, Python! 🐍")

Hello, Python! 🐍


🎉 **You just ran your first program.** The `print(...)` command tells Python to display whatever is between the parentheses.

A first orientation in how Python code is laid out:

- Python reads a cell **top to bottom**, one statement per line, and does exactly what each line says — in that order.
- Everything after a `#` is a **comment**: for human readers only, ignored by Python.
- Python also cares about **line structure**: the spaces at the *start* of a line are meaningful, not decoration. We don't need that yet — it becomes the star of Notebook 3.

And two practical tips for the session:

- What matters is the order in which you **run** cells, not the order they appear on the page. If things ever feel tangled, use **Runtime → Restart and run all** (Colab) to start fresh.
- You cannot break anything. Experiment freely — errors are how everyone learns to code.

### 💬 Discuss (30 seconds, with your neighbour)

Where have you already encountered something built with data or AI in *your* field of study or daily life?

## 2. Variables — labelled boxes for your data

Before a computer can *work* with a value, it needs somewhere to *keep* it. A **variable** is a name attached to a value — think of it as a **labelled box**:

```
┌──────────┐    ┌───────┐    ┌──────────┐
│  "Alice" │    │  25   │    │   1.70   │
└────┬─────┘    └───┬───┘    └────┬─────┘
     │              │             │
   name            age         height
```

You put a value into a box with the `=` sign (read it as *"gets"*, not *"equals"*): `age = 25` means *"the box labelled `age` gets the value 25"*. From then on, writing `age` anywhere means *"look inside that box"*.

In [4]:
name = "Alice"      # text goes in quotes
age = 25            # a whole number
height = 1.70       # a decimal number

print(name)
print(age)
print(height)

# Variables can be reused and combined:
birth_year = 2026 - age
print(birth_year)

Alice
25
1.7
2001


**Reading the output:** the first three lines simply show what is inside each box. One tiny surprise: we typed `1.70`, but Python printed `1.7` — Python stores the *value* of a number, not how you typed it. (Making numbers look nice for humans is a separate job, and Section 5 has a tool for exactly that.) The last line shows the real power: we *computed* a new value from an existing one. If `age` changes, we edit one place and everything downstream updates.

Two naming rules to remember (there are more, but these carry you far):

- Names are written in `snake_case`: lowercase words joined by underscores, e.g. `birth_year`, `coffee_price`.
- Choose names that say what the value *means* — `temperature` beats `t`.

### 🎯 Try it (1–2 min) — Your own boxes

In the cell below, create **two variables**: `my_name` (your name, in quotes) and `my_age` (a number). Then `print` both. Run the cell to check.

In [5]:
# Your turn 👇  Replace the example values with your own, then press Shift + Enter.

my_name = "..."
my_age = 0

print(my_name)
print(my_age)

...
0


<details><summary>💡 Click to reveal the solution</summary>

```python
my_name = "Ada"
my_age = 36

print(my_name)
print(my_age)
```

**Reasoning.** Text must be wrapped in quotes (`"Ada"`), numbers must not (`36`). If you forget the quotes around a name, Python thinks you mean a *variable* called `Ada` — which doesn't exist — and complains with a `NameError`. That error message is your friend: it tells you exactly which name Python couldn't find.
</details>

## 3. Data types — not all values are alike

Look at a spreadsheet from any field: some columns hold whole numbers (participants), some hold decimals (measurements), some hold text (city names), and some hold yes/no answers. Python makes the same distinction. The four types you will meet every single day:

| Type | Python name | Example | Typical use |
|------|-------------|---------|-------------|
| Whole number | `int` | `42` | counts, years, IDs |
| Decimal number | `float` | `19.99` | measurements, prices, averages |
| Text ("string") | `str` | `"Berlin"` | names, labels, answers |
| Yes/No | `bool` | `True`, `False` | flags, comparison results |

You can always *ask* Python what type a value has, using `type()`:

In [6]:
participants = 42          # int
average_temp = 21.5        # float
city = "Berlin"            # str
survey_complete = True     # bool

print(type(participants))
print(type(average_temp))
print(type(city))
print(type(survey_complete))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


**Reading the output:** `<class 'int'>` looks more dramatic than it is. The word in quotes is the answer — `int`, `float`, `str`, `bool`. (`class` is simply Python's own word for "kind of value"; you can ignore it for now.)

**Why care about types?** Because types decide what you can *do* with a value. You can multiply two numbers, but `"Berlin" * "Hamburg"` makes no sense — and Python will say so. The most common beginner trip-up: `"42"` (with quotes) is *text*, not a number. `"42" + 1` produces an error; `42 + 1` produces `43`.

### 🎯 Try it (1–2 min) — Guess the type

Before running the cell below, **predict** the type of each value. Then run it and check your guesses. (Hint for the last line: read `7 > 3` as a *question* — "is 7 greater than 3?" What kind of answer does a yes/no question get?)

In [7]:
# Predict first, then run!
print(type(7))
print(type(7.0))
print(type("7"))
print(type(7 > 3))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


<details><summary>💡 Click to reveal the solution</summary>

```text
<class 'int'>     # 7      — a whole number
<class 'float'>   # 7.0    — the decimal point makes it a float, even with .0
<class 'str'>     # "7"    — quotes make it text, no matter what's inside
<class 'bool'>    # 7 > 3  — a comparison, and its answer is True
```

**Reasoning.** The last one is the interesting case: `7 > 3` is a *question* ("is 7 greater than 3?"), and Python answers with a boolean — `True`. Comparisons producing `True`/`False` become the engine of decision-making in Notebook 3.
</details>

## 4. Arithmetic — Python as a very reliable calculator

Python knows the operators from school maths:

| Operator | Meaning | Example | Result |
|----------|---------|---------|--------|
| `+` | addition | `7 + 3` | `10` |
| `-` | subtraction | `7 - 3` | `4` |
| `*` | multiplication | `7 * 3` | `21` |
| `/` | division | `7 / 2` | `3.5` |
| `**` | power | `2 ** 10` | `1024` |

Let's combine variables and arithmetic for a tiny real calculation — what a daily coffee habit costs per year:

In [8]:
coffee_price = 3.20        # euros per cup
cups_per_day = 2
days_per_year = 365

yearly_cost = coffee_price * cups_per_day * days_per_year
print("Coffee per year, in euros:")
print(yearly_cost)

Coffee per year, in euros:
2336.0


**Reading the output:** `2336.0` — that daily habit is a small holiday per year! But why the `.0` on a euro amount? Because `coffee_price` is a `float`, and as soon as a decimal number is involved, the result is a decimal number too. (Division with `/` *always* gives a `float`, even for `6 / 2`.) The types from Section 3 quietly at work.

## 5. Strings and f-strings — talking about your results

A bare number (`2336.0`) is not a result — *"Coffee costs you €2,336.00 per year"* is. Combining text and values is such a common job that Python has a dedicated tool for it: the **f-string**.

Put an `f` before the opening quote, and you can embed any variable — or a small calculation — inside curly braces `{ }`. After a colon you can add a **format instruction**; the two you will use most in data work are `:.2f` (exactly two decimal places) and `:,` (thousands separator).

In [9]:
name = "Alice"
age = 25

# Embedding values — even small calculations work inside { }
print(f"{name} is {age} years old.")
print(f"Next year, {name} will be {age + 1}.")

# Formatting numbers
print(f"Coffee per year: {yearly_cost:.2f} euros")      # exactly 2 decimals
print(f"Nicely readable: €{yearly_cost:,.2f}")          # separators + 2 decimals

Alice is 25 years old.
Next year, Alice will be 26.
Coffee per year: 2336.00 euros
Nicely readable: €2,336.00


### 🎯 Try it (1–2 min) — A proper sentence

A restaurant bill of **63.75 euros** is split between **4 people**. Using the variables below, compute what each person pays and print exactly:

**`Each of the 4 guests pays 15.94 euros.`**

(One f-string, with `:.2f` for the amount.)

In [8]:
# Your turn 👇
bill = 63.75
people = 4

# per_person = ...
# print(f"...")

<details><summary>💡 Click to reveal the solution</summary>

```python
bill = 63.75
people = 4

per_person = bill / people
print(f"Each of the {people} guests pays {per_person:.2f} euros.")
```

**Reasoning.** `bill / people` is `15.9375` — printed raw, that is an unreadable amount of money. `:.2f` rounds it to two decimals *for display only*; the variable itself keeps its full precision. Small formatting choices like this decide whether people can actually *read* your analysis.
</details>

## 6. Putting it all together — a tiny report

Everything from this notebook in one place: variables hold the inputs, arithmetic derives the numbers, f-strings turn them into a sentence a human wants to read. Here is a summer-school organiser's catering estimate:

Change one input above — say `participants = 40` — and re-run the cell: the whole report updates itself. That, in miniature, is what data analysis with Python *is*.

## 🧠 Key takeaways

1. A notebook mixes **text cells** and **code cells**; run code with **Shift + Enter**. Run order matters.
2. Python executes a cell **top to bottom**, one statement per line; `#` starts a **comment** for humans only.
3. **Variables** are labelled boxes: `age = 25` stores a value, and descriptive `snake_case` names keep code readable.
4. The four core **types** are `int`, `float`, `str`, `bool` — check any value with `type()`. `"42"` (text) is not `42` (number)!
5. **Arithmetic** uses `+ - * / **`; `/` always gives a `float`.
6. **f-strings** — `f"...{value}..."` — build readable output; `:.2f` fixes the decimals, `:,` adds thousands separators.

## ✅ Self-assessment

Tick each box you can honestly check — and don't worry if some are shaky, the next notebooks reinforce all of them:

- [ ] I can run a notebook cell and explain what `print()` does
- [ ] I can create variables and explain the "labelled box" idea
- [ ] I can name the four core data types and use `type()` to check a value
- [ ] I can explain why `"42" + 1` fails but `42 + 1` works
- [ ] I can compute something useful with `+ - * / **`
- [ ] I can put a value into a sentence with an f-string and format it with `:.2f`

## 🚀 Next step

Continue with **Notebook 2 — Data Structures** ([`02_data_structures.ipynb`](02_data_structures.ipynb)): so far every box has held exactly *one* value, but real data comes in series and tables. That notebook introduces **lists**, **tuples** and **dictionaries** — the containers that hold many values at once.

> **Want to go deeper after the session?** The self-paced track in [`../02_advanced_self_learning/`](../02_advanced_self_learning/) revisits everything from today in more depth (starting with `01_python_basics.ipynb`) and continues all the way to machine learning.